// The embedded client lives in client/, generated from the JavaScript build. A checkout without it
// would fail inside `include_str!` with a bare "file not found"; this names the fix instead.
fn main() {
    println!("cargo:rerun-if-changed=client/manifest.rs");
    println!("cargo:rerun-if-changed=client/plugins.rs");
    let needs_client = std::env::var_os("CARGO_FEATURE_CLIENT").is_some()
        || std::env::var_os("CARGO_FEATURE_SCAN").is_some();
    if needs_client && !std::path::Path::new("client/manifest.rs").exists() {
        panic!(
            "sigmx: client/ is missing. It is generated by `npm run build` at the root of the sigmx \
             repository (published crates include it). Run that first, or disable the `client` and \
             `scan` features."
        );
    }
}
