// Copies the built client into the Rust SDK (sdks/rust/client) and writes the Rust sources that embed it:
// the script-tag build, the ESM tree a bundler-free Rust project can unpack, and the plugin table the
// Rust scanner needs. Runs at the end of `npm run build`; the directory is generated, never edited.
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { builtinPlugins } from '../dist/kernel/scan.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
const out = join(root, 'sdks', 'rust', 'client');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

// Browser-side modules only: the Node-only scanner, precompiler, CLI, Vite plugin and server helpers stay out.
const EXCLUDE = new Set(['cli.js', 'vite.js', 'server.js', 'kernel/scan.js', 'kernel/precompile.js']);
const walk = (dir, acc = []) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, acc);
    else if (e.name.endsWith('.js') && !e.name.endsWith('.map')) acc.push(p);
  }
  return acc;
};

rmSync(out, { recursive: true, force: true });
mkdirSync(join(out, 'esm'), { recursive: true });

const standalone = readFileSync(join(dist, 'sigmx.standalone.js'), 'utf8');
writeFileSync(join(out, 'sigmx.standalone.js'), standalone);
const etag = `"${createHash('sha256').update(standalone).digest('hex').slice(0, 16)}"`;

const files = walk(dist)
  .map((p) => relative(dist, p).split('\\').join('/'))
  .filter((p) => p !== 'sigmx.standalone.js' && !EXCLUDE.has(p))
  .sort();
for (const f of files) {
  mkdirSync(dirname(join(out, 'esm', f)), { recursive: true });
  writeFileSync(join(out, 'esm', f), readFileSync(join(dist, f)));
}

const rs = (s) => JSON.stringify(s);
writeFileSync(
  join(out, 'manifest.rs'),
  `// Generated by scripts/rust-client.mjs from sigmx ${version}. Do not edit.
/// Version of the embedded client.
pub const VERSION: &str = ${rs(version)};
/// ETag of the script-tag build (a hash of its content, quoted).
pub const ETAG: &str = ${rs(etag)};
/// The script-tag build: every plugin, minified, starts on load and exposes \`window.sigmx\`.
pub const STANDALONE: &str = include_str!("sigmx.standalone.js");
/// The ES module tree as (path, source) pairs: \`kernel/index.js\`, \`plugins/index.js\`, \`presets/all.js\`, …
pub const FILES: &[(&str, &str)] = &[
${files.map((f) => `    (${rs(f)}, include_str!(${rs(`esm/${f}`)})),`).join('\n')}
];
`,
);

// Each built-in's own module, from the barrel's re-exports, so a generated entry can import the
// selected plugins directly instead of through plugins/index.js (which drags every plugin into
// bundlers that do not tree-shake re-exports, and into a browser loading the tree unbundled).
const modules = new Map();
for (const m of readFileSync(join(dist, 'plugins/index.js'), 'utf8').matchAll(
  /import\s*\{([^}]*)\}\s*from\s*["']\.\/([^"']+)["']/g,
)) {
  for (const name of m[1].split(',')) {
    const local = name
      .trim()
      .split(/\s+as\s+/)
      .pop();
    if (local) modules.set(local, `plugins/${m[2]}`);
  }
}
const moduleOf = (p) => {
  const m = modules.get(p.export);
  if (!m) throw new Error(`no module found for plugin export "${p.export}" in dist/plugins/index.js`);
  return m;
};

const kind = { attribute: 'Kind::Attribute', action: 'Kind::Action', handler: 'Kind::Handler' };
writeFileSync(
  join(out, 'plugins.rs'),
  `// Generated by scripts/rust-client.mjs from sigmx ${version}. Do not edit.
/// Every plugin in \`sigmx/plugins\`, with the name the scanner looks for.
pub static BUILTIN: &[BuiltinMeta] = &[
${builtinPlugins()
  .map(
    (p) =>
      `    BuiltinMeta { export: ${rs(p.export)}, name: ${rs(p.name)}, kind: ${kind[p.type]}, module: ${rs(moduleOf(p))}, literal: ${!!p.literal}, args: &[${(p.args ?? []).map(rs).join(', ')}] },`,
  )
  .join('\n')}
];
`,
);
console.log(`wrote sdks/rust/client/: standalone, ${files.length} modules, plugin table (${version})`);
